### PR TITLE
Flutter error management

### PR DESCRIPTION
**Pull request by evdokimovs**
## Synopsis

Этот PR реализует механизм уведомления конечного приложения о панике, произошедшей в Расте, а также детектирование ошибок, возвращенных из Флаттера Расту.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed
    - [x] `flutter-webrtc` dependency switched back to `master` branch

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by evdokimovs** [comment]
## FCM

```
Flutter error management (#28)

- add `on_panic` callback to the Dart side
- detect returned from Flutter errors in Rust
```

**Review by alexlapa — CHANGES_REQUESTED** [review]
@evdokimovs ,

Sync with mainline.

**Review by alexlapa — APPROVED** [review]

**Review by tyranron — APPROVED** [review]

**Comment by tyranron** [comment]
Don't merge.

**Comment by evdokimovs** [comment]
@tyranron ,

Мне запушивать запрошенные изменения, или были обнаружены еще какие-то неучтенные моменты?

**Comment by tyranron** [comment]
But GitHub Actions still seem to be outaged. We need to wait.

**Comment by tyranron** [comment]
@evdokimovs Flutter tests stuck all the time. Please, fix them in a separate PR.

**Pull request merged**
