### PR TITLE
Migrate to forked Cucumber 0.10

### PR DESCRIPTION
**Pull request by ilslv**
## Synopsis

Upgrade to a new version of `cucumber_rust`.

## Solution

Introduce concurrent tests runner.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by ilslv** [comment]
@tyranron there is a problem, while running concurrent tests for firefox, because geckodriver doesn't support concurrent sessions: https://github.com/mozilla/geckodriver/issues/1523#issuecomment-473282868, https://github.com/jonhoo/fantoccini/issues/111#issuecomment-727650629. While chrome works just fine.

There already was an effort to hack around this: https://github.com/jonhoo/fantoccini/pull/100. We can try merging this (seems like pretty straightforward task) or just run tests as `@serial` in case of firefox.

**Comment by ilslv** [comment]
@tyranron we'll have to fallback to serial scenario execution, because even if we'll have multiple connections to single `WebDriver` client, we won't get isolation. This means, if one connection will redirect to `foo.com` and later second connection will redirect to `bar.com`, first connection will work with `foo.com`.

**Comment by tyranron** [comment]
@ilslv can we enable serial execution just for Firefox and leave it concurrent for Chrome?

**Comment by ilslv** [comment]
@tyranron yep, already done that

**Comment by tyranron** [comment]
@ilslv ok, that will do then! Just leave a fat comment explaining why that is done and we're ready for review, I guess.

**Comment by ilslv** [comment]
## FCM

```
Migrate to forked Cucumber 0.10 (#3)
```

**Review by tyranron — APPROVED** [review]

**Comment by ilslv** [comment]
@tyranron I've decreased `max_concurrent_scenarios` to 5 to avoid `hyper` `IncompleteMessage` and `CannelClosed` errors. Locally I've been running with `debug=no` and 10 `max_concurrent_scenarios` just fine and got confused, once haven't find this option on `CI`. Is there a reason `CI` tests are running in `debug`?

**Comment by tyranron** [comment]
@ilslv no, I think it has sense to run CI in release mode.

**Pull request merged**
